### ISSUE TITLE
Change json_decoder

### ISSUE THREAD

**Issue by rafbgarcia** [absinthe-graphql/absinthe_plug#174]
I'm using Jason as json library, but I can't manage to make it work with absinthe_plug, I get the following error:

``` 
Exception:

    ** (UndefinedFunctionError) function Poison.decode/1 is undefined (module Poison is not available)
        Poison.decode("{}")
        (absinthe_plug) lib/absinthe/plug/request/query.ex:118: Absinthe.Plug.Request.Query.decode_variables/2
        (absinthe_plug) lib/absinthe/plug/request/query.ex:52: Absinthe.Plug.Request.Query.parse/3
        (absinthe_plug) lib/absinthe/plug/request.ex:71: Absinthe.Plug.Request.build_request/4
        (absinthe_plug) lib/absinthe/plug/request.ex:49: Absinthe.Plug.Request.parse/2
        (absinthe_plug) lib/absinthe/plug.ex:340: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:240: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
```

And I have this in place:

```ex
plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
```

```
iex(1)> Phoenix.json_library()
Jason
```

Any ideas how to do that?

**Comment by rafbgarcia** [comment]
Ty @benwilson512.

For reference:

```
  scope "/api" do
    pipe_through :api

    post("/", Absinthe.Plug.GraphiQL, schema: MyApp.Graphql.Schema, json_codec: Phoenix.json_library())
  end
```

**Comment by benwilson512** [comment]
FYI you probably want to `forward` when using GraphiQL, otherwise it will be unable to show the HTML UI.

**Comment by ar1a** [comment]
This errors out by default, consider changing the default json codec to Jason now?
