### ISSUE TITLE
why status is 200 when argument invalid since absinthe_plug 1.4.6?

### ISSUE THREAD

**Issue by scottming** [absinthe-graphql/absinthe_plug#195]
I'm reading your great book. but when I update the absinthe_plug to 1.4.6. These test code will not pass:

```elixir
  @query """
  {
    menuItems(matching: 123) {
      name
    }
  }
  """
  test "menuItems field returns errors when using a bad value" do
    response = get(build_conn(), "/api", query: @query)
    assert %{"errors" => [
      %{"message" => message}
    ]} = json_response(response, 400)
    assert message == "Argument \"matching\" has invalid value 123."
  end
```
when I run 
```bash
$ mix test test/plate_slate_web/schema/query/menu_items_test.exs
```
I got a confuse error:

```elixir
  1) test menuItems field returns errors when using a bad value (PlateSlateWeb.Schema.Query.MenuItemsTest)
     test/plate_slate_web/schema/query/menu_items_test.exs:74
     ** (RuntimeError) expected response with status 400, got: 200, with body:
     {"errors":[{"message":"Argument \"matching\" has invalid value 123.","locations":[{"line":2,"column":0}]}]}
     code: ]} = json_response(response, 400)
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:362: Phoenix.ConnTest.response/2
       (phoenix) lib/phoenix/test/conn_test.ex:408: Phoenix.ConnTest.json_response/2
       test/plate_slate_web/schema/query/menu_items_test.exs:78: (test)



Finished in 0.3 seconds
4 tests, 1 failure
```

As I know, when the params invalid, HTTP code should be 400, not 200.

Is this a bug?

**Comment by maartenvanvliet** [comment]
The GraphQL spec prescribes returning a 200 code in all cases, even those where there is an error. HTTP error codes are specific to the HTTP transport, and GraphQL is transport-independent. 

Older versions of absinthe_plug did return error codes besides 200, that is probably why the book has code with the 400 error code. The latest versions of absinthe_plug however do use the 200 code.
