### ISSUE TITLE
How do I test file upload

### ISSUE THREAD

**Issue by lstrzebinczyk** [absinthe-graphql/absinthe_plug#227]
Hello

I am working on uploading a file to my absinthe api in a mutation. I have a definition like this:

```
    field :register_offset, non_null(:camera) do
      arg(:camera_id, non_null(:id))
      arg(:offset, :integer)
      arg(:film, :upload)

      middleware(ScorebreakWeb.Graphql.Middlewares.Authenticate)
      resolve(&ScorebreakWeb.Graphql.Mutations.RegisterOffset.resolve/2)
    end
```

And if a, :upload is passed, I am performing logic. This is working well with live application, but I need a test to make sure it stays this way. I did try to just simply

```
      upload = %Plug.Upload{
        content_type: "video/mp4",
        path: "test/assets/camera_registration_test.mp4",
        filename: "camera_registration_test.mp4"
      }
```

and send this to `conn` with a query, but it fails, since 

```
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Plug.Upload{content_type: "video/mp4", filename: "camera_registration_test.mp4", path: "test/assets/camera_registration_test.mp4"} of type Plug.Upload (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Map, HashDict, List, Range, IO.Stream, HashSet, Function, GenEvent.Stream, Stream, Date.Range, MapSet, File.Stream
```

I understand that this would happen, since it probably is called here: https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/types.ex#L64

The only way to test it mentioned in the docs is to write a curl, but that hardly is a good way.
So my question is: How do I reasonably write a test alongside my other absinthe/phoenix application tests, that makes sure file upload handled by :upload type from absinthe_plug work well?

**Comment by benwilson512** [comment]
You can find an example within the Absinthe.Plug tests: https://github.com/absinthe-graphql/absinthe_plug/blob/master/test/lib/absinthe/plug_test.exs#L311

**Comment by lstrzebinczyk** [comment]
I did look at these tests, but this is a very different testing environment, I wasn't able to translate it to a test in phoenix app. I've seen some advices to use Plug.Upload, also in the file you mentioned, so I'm trying to do something like this:

```
    test "actually updates the with a film", %{conn: conn} do
      film = %Plug.Upload{
        content_type: "video/mp4",
        path: "test/assets/camera_registration_test.mp4",
        filename: "camera_registration_test.mp4"
      }

      result =
        conn
        |> post("/api/v1/graphql", query: @query, variables: %{film: film})
        |> json_response(200)

      assert result == -2
    end
```

And I am getting the mentioned error. Also, the stacktrace, if it's any helpful:

```
     stacktrace:
       (elixir 1.10.2) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir 1.10.2) lib/enum.ex:141: Enumerable.reduce/3
       (elixir 1.10.2) lib/enum.ex:3383: Enum.map/2
       (absinthe 1.5.0-rc.4) lib/absinthe/blueprint/input.ex:75: Absinthe.Blueprint.Input.parse/1
       (absinthe 1.5.0-rc.4) lib/absinthe/phase/document/variables.ex:64: anonymous fn/3 in Absinthe.Phase.Document.Variables.update_operation/2
       (elixir 1.10.2) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.10.2) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (absinthe 1.5.0-rc.4) lib/absinthe/phase/document/variables.ex:63: Absinthe.Phase.Document.Variables.update_operation/2
       (absinthe 1.5.0-rc.4) lib/absinthe/phase/document/variables.ex:55: anonymous fn/3 in Absinthe.Phase.Document.Variables.update_operations/2
       (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
       (absinthe 1.5.0-rc.4) lib/absinthe/phase/document/variables.ex:54: Absinthe.Phase.Document.Variables.update_operations/2
       (absinthe 1.5.0-rc.4) lib/absinthe/phase/document/variables.ex:49: Absinthe.Phase.Document.Variables.run/2
       (absinthe 1.5.0-rc.4) lib/absinthe/pipeline.ex:367: Absinthe.Pipeline.run_phase/3
       (absinthe_plug 1.5.0-rc.2) lib/absinthe/plug.ex:445: Absinthe.Plug.run_query/4
       (absinthe_plug 1.5.0-rc.2) lib/absinthe/plug.ex:258: Absinthe.Plug.call/2
       (phoenix 1.4.16) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
       (phoenix 1.4.16) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (scorebreak 0.1.0) lib/plug/error_handler.ex:65: ScorebreakWeb.Router.call/2
       (scorebreak 0.1.0) lib/scorebreak_web/endpoint.ex:1: ScorebreakWeb.Endpoint.plug_builder_call/2
       (scorebreak 0.1.0) lib/scorebreak_web/endpoint.ex:1: ScorebreakWeb.Endpoint.call/2
```

Maybe it's a bug?

**Comment by lstrzebinczyk** [comment]
I figured out a way, kind of by accident. I'll leave it here for anybody who stumbles across the same issue:

```
result =
        conn
        |> post("/api/v1/graphql", query: @query, variables: %{film: "film"}, film: film)
        |> json_response(200)
```

Specifically send another variable with a request in body that is the Plug.Upload, and in graphql variables pass in the name of a variable holding that Plug.Upload.

Maybe I could send a PR with an example on how to get this done added to docs? It looks like it would be a fairly common use case.

**Comment by benwilson512** [comment]
PR is welcome!
