### ISSUE TITLE
Unused variables throws exceptions

### ISSUE THREAD

**Issue by fazibear** [absinthe-graphql/absinthe_plug#40]
Query with unused variable:

```elixir
query($userId: String!, $test: String!) {
    user(id: $userId) {
        id
    }
}
```

throws:

```10:55:00.992 [error] #PID<0.2477.0> running Taped.Web.Router terminated
Server: localhost:4000 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Absinthe.Phase.Document.Result.format_location/1
        (absinthe) lib/absinthe/phase/document/result.ex:116: Absinthe.Phase.Document.Result.format_location(nil)
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/result.ex:111: Absinthe.Phase.Document.Result.format_error/1
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (absinthe) lib/absinthe/phase/document/result.ex:42: Absinthe.Phase.Document.Result.format_result/1
        (absinthe) lib/absinthe/phase/document/result.ex:12: Absinthe.Phase.Document.Result.run/2```

**Comment by bruce** [comment]
Thanks for reporting this!

Notably, this document _should_ instead cause a validation error due to Absinthe.Phase.Document.Validation.NoUnusedVariables (but that should obviously be a nice GraphQL error vs what you're seeing here).

**Comment by bruce** [comment]
Oh, actually -- this is an issue with https://github.com/absinthe-graphql/absinthe, not absinthe_plug. I'll open an issue over there instead. In the future, please file issues here only if they're clearly plug-related.
