### ISSUE TITLE
(KeyError) key :no_query_message not found

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/absinthe_plug#50]
Using 

**absinthe 1.2.5**
**absinthe_plug 1.2.2**

When I run the following introspection query

```graphql
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

I get the following error

```
 ** (KeyError) key :no_query_message not found in: %{adapter: nil, context: %{}, interface: :advanced, json_codec: %{module: Poison, opts: []}, pipeline: {Absinthe.Plug, :default_pipeline}, schema_mod: Core.GraphQL.Schema}
        lib/absinthe/plug.ex:146: Absinthe.Plug.execute/2
        lib/absinthe/plug.ex:115: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:154: Phoenix.Router.Route.forward/4
        (webapp) lib/phoenix/router.ex:261: Webapp.Router.dispatch/2
        (webapp) web/router.ex:1: Webapp.Router.do_call/2
        (webapp) lib/webapp/endpoint.ex:1: Webapp.Endpoint.phoenix_pipeline/1
        (webapp) lib/plug/debugger.ex:123: Webapp.Endpoint."call (overridable 3)"/2
        (webapp) lib/webapp/endpoint.ex:1: Webapp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

At this moment I couldn't run other query because I'm using the `require('graphql/utilities').introspectionQuery` from Javascript to start my babelRelayPlugin. I'll see if I can generate the schema with `mix absinthe.schema.json` so I can try other queries.

**Comment by hisapy** [comment]
I'm closing this. I removed **_build** and recompiled my **deps** again and couldn't reproduce the error anymore.
