### ISSUE TITLE
"No schema available" in graphiql

### ISSUE THREAD

**Issue by tpitale** [absinthe-graphql/absinthe_plug#90]
I've got graphiql mounted in dev and I'm able to make mutations as per my schema. But, the "docs" tab only shows "NO SCHEMA AVAILABLE".

I'm wondering if this is supposed to work (indicating I probably have it misconfigured), or if this is not a feature of absinthe_plug.

Thanks!

```ex
  if Mix.env == :dev do
    forward "/graphiql",
      Absinthe.Plug.GraphiQL,
      schema: DeviceService.Api.Factory.Schema,
      interface: :simple
  end
```

**Comment by benwilson512** [comment]
Can you show a screen shot of the error or something? Can you check the javascript console for errors? Finally, are you able to post your schema here or is it too large / private?

**Comment by tpitale** [comment]
First state when loading graphiql:

<img width="1350" alt="screen shot 2017-06-13 at 1 36 33 pm" src="https://user-images.githubusercontent.com/163/27098455-400dfc1c-503d-11e7-9dfb-bf7ce07b24b2.png">

**Comment by tpitale** [comment]
JS console shows no errors.

**Comment by tpitale** [comment]
@benwilson512 Would you like the schema as JSON or Elixir?

**Comment by benwilson512** [comment]
Elixir please.

**Comment by tpitale** [comment]
```ex
defmodule DeviceService.Api.Factory.Schema do
  use Absinthe.Schema

  import_types DeviceService.Api.Factory.Schema.Types

  query do
  end

  mutation do
    @desc "Create a batch of generated keys"
    field :key_batch, type: :key_batch do
      arg :count, non_null(:integer)
      arg :last_batch_id, :integer

      resolve &DeviceService.Api.Factory.KeyBatchResolver.build/2
    end

    @desc "Submit test results for a device"
    field :device_test_results, type: :device_test_results do
      arg :data, list_of(:device_test_input)

      resolve &DeviceService.Api.Factory.DeviceTestResolver.accept/2
    end
  end
end
```

**Comment by benwilson512** [comment]
The issue seems to be with your types, can you show those too?

**Comment by tpitale** [comment]
```ex
defmodule DeviceService.Api.Factory.Schema.Types do
  use Absinthe.Schema.Notation

  object :generated_key, name: :key do
    field :id, :id
    field :key, :string
  end

  object :key_batch do
    field :id, :id

    field :generated_keys, list_of(:key), name: "keys"
  end

  object :device_test do
    field :id, :id
    field :device_id, :integer
  end

  object :device_test_results do
    field :device_tests, list_of(:device_test), name: "results"
  end

  input_object :device_test_input do
    field :device_id, non_null(:integer)

    field :iccid, non_null(:string)
    field :address, non_null(:ip_address)

    field :results, non_null(:json)
  end

  scalar :json do
    description "JSON to/from String"

    parse fn input ->
      case Poison.decode(input.value) do
        {:ok, result} -> {:ok, result}
        _ -> :error
      end
    end

    serialize &Poison.encode!/1
  end

  scalar :ip_address do
    description "Postgrex.INET to/from String"

    parse fn input ->
      case (input.value |> to_charlist |> :inet.parse_address) do
        {:ok, address} -> {:ok, %Postgrex.INET{address: address}}
        {:error, _reason} -> nil
      end
    end

    serialize fn inet ->
      inet.address |> Tuple.to_list |> Enum.join(".")
    end
  end
end
```

**Comment by benwilson512** [comment]
Interesting I'll look into it. You're like the first person to use the `name` option a bunch on fields, why are you doing that btw?

**Comment by tpitale** [comment]
Matching internal data model to expected json output.

**Comment by yordis** [comment]
@tpitale just in case, clean up `local storage` of the browser and see what happen. I ran into an issue with `graphiql` tool  failing because of that.

**Comment by tpitale** [comment]
Does anyone else see this error ever?
```
invariant@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:12:28271
defineFieldMap@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:14:245
getFields@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:14:5846
http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:6016
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:6179
reduce@[native code]
e@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:9277
buildClientSchema@http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:31817
http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:2:13359
promiseReactionJob@[native code]
```

**Comment by tpitale** [comment]
@yordis Thanks for the suggestion. I'm not seeing anything in local storage, cookies, et al. Clearing doesn't seem to be an option at this time. Gonna try other browsers.

**Comment by tpitale** [comment]
Ahhhh! Chrome gives a better error:

```
Error: RootQueryType fields must be an object with field names as keys or a function which returns such an object.
    at invariant (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:12:28262)
    at defineFieldMap (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:14:245)
    at exports.GraphQLObjectType.e.getFields (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:14:5832)
    at http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:6007
    at typeMapReducer (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:6179)
    at Array.reduce (native)
    at new e (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:9271)
    at buildClientSchema (http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:15:31792)
    at http://cdn.jsdelivr.net/graphiql/0.9.3/graphiql.min.js:2:13359
    at <anonymous>
```

**Comment by tpitale** [comment]
Removing all `name`s yields the same error in Chrome

**Comment by tpitale** [comment]
Updated types:

```ex
defmodule DeviceService.Api.Factory.Schema.Types do
  use Absinthe.Schema.Notation

  object :generated_key do
    field :id, :id
    # field :serial_number (id + 1_000_000_000)
    field :key, :string
  end

  object :key_batch do
    field :id, :id

    field :keys, list_of(:generated_key), resolve: resolve_as(:generated_keys)
  end

  object :device_test do
    field :id, :id
    field :device_id, :integer
  end

  # field &1: name in map from resolver; &2: type of object in schema.types; &3: json output key
  object :device_test_results do
    field :results, list_of(:device_test), resolve: resolve_as(:device_tests)
  end

  # snip …

  defp resolve_as(key) do
    fn(parent, _, _) -> {:ok, Map.get(parent, key)} end
  end
end

**Comment by tpitale** [comment]
Resolved: `query` can not be empty for graphiql. Put something like:

```ex
field :health, :string, resolve: fn _, _ -> {:ok, "up"} end
```

 To have something there.

**Comment by Gabriel-Andy** [comment]
I have a similar pb now 
my console.log seems to be ok
I need because no schema is available
